---
- name: Setup Web Server
  hosts: all
  remote_user: root

  tasks:
  - name: Install Apache Server
    apt: 
      name: apache2
      state: present
  - name: Add Sample file
    command: echo "This my first ansible" > /var/www/html/index.html
  - name: Set Time Module to Africa/Lagos 
    timezone:
      name: Africa/Lagos
  - name: copy file from localhost(this VM) to remote server
    copy:
      src: /home/miracool/Alt-school-related/index.php
      dest: /var/www/html/index.php
  - name: Get the status of apache2 service
    command: systemctl status apache2
